name: Upload to CurseForge

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create zip
        run: |
          mkdir AntiSocial
          cp *.lua *.toc AntiSocial/
          cp -r Libs AntiSocial/
          zip -r AntiSocial.zip AntiSocial

      - name: Upload to CurseForge
        uses: itsmeow/curseforge-upload@v3
        with:
          token: "${{ secrets.ANTISOCIAL }}"
          project_id: "1549903"
          game_endpoint: "wow"
          file_path: "AntiSocial.zip"
          game_versions: "12.1.0"
          release_type: "release"
          display_name: "AntiSocial - ${{ github.event.head_commit.timestamp }}"
          changelog: "${{ github.event.head_commit.message }}"
          changelog_type: "markdown"
